export const Status = {
    UNINITIALIZED: 0,
    PENDING: 1,
    CANCELLED: 2,
    SUCCESSFUL: 3,
    FAILED_AMOUNT_TOO_LARGE: 4,
    FAILED_EXPIRED: 5,
    FAILED_INSUFFICIENT_OUTPUT: 6,
    FAILED_INCENTIVE_NOT_FOUND: 7,
    FAILED_INCENTIVE_NOT_QUALIFIED: 8,
    FAILED_UNHANDLED: 9
};
