// Types
import type { FC, ReactElement } from 'react';

// Libraries
import { useState, useCallback } from 'react';

// Contexts
import { useWeb3Context } from '@contexts/web3';

// Code
import Modal from '@components/ui/Modal';

const PARAGRAPH_BREAK = <span className="block h-4"></span>;
const PARAGRAPHS = [
    {
        title: 'Introduction',
        text: (
            <>
                Transparent Protocol aims to exploit the advantages of on- chain atomic operations
                and protocols so as to provide relatively stable and uncorrelated returns across the
                cryptoverse.
            </>
        )
    },
    {
        title: 'Informational Purposes',
        text: (
            <>
                The information set out in this document is provided solely for INFORMATIONAL
                PURPOSES and does not constitute any binding commitment. Please do not rely on this
                information in making purchasing decisions because ultimately, the development,
                release, and timing of any features or functionality remains at the sole discretion
                of the Project, and is subject to change. Further, the Disclaimer, Whitepaper or the
                Website may be amended or replaced from time to time. There are no obligations to
                update the Disclaimer, Whitepaper or the Website, or to provide recipients with
                access to any information beyond what is provided herein.
                {PARAGRAPH_BREAK}
                No regulatory authority has examined or approved, whether formally or informally, of
                any of the information set out in the Disclaimer, Whitepaper or the Website. No such
                action or assurance has been or will be taken under the laws, regulatory
                requirements or rules of any jurisdiction. The publication, distribution or
                dissemination of the Disclaimer, Whitepaper or the Website does not imply that the
                applicable laws, regulatory requirements or rules have been complied with.
            </>
        )
    },
    {
        title: 'Engaging with Transparent Protocol',
        text: (
            <>
                Holders stake BUSD to mint Transparent tokens. When the value of Transparent&apos;s
                portfolio grows, the value of Transparent&apos;s tokens will grow to reflect that,
                and that represents the growth of the original BUSD.
                {PARAGRAPH_BREAK}
                For every 1% of returns generated by Transparent, 0.3% of returns will be minted as
                Transparent and distributed back to the Protocol owners. Other than this incentive
                system, Transparent has no other fee mechanisms.
            </>
        )
    },
    {
        title: 'Openly Auditable Anti-Rug Pull Mechanisms',
        text: (
            <>
                Transparent has a list of protocols that it can interact with, so as to prevent
                unauthorised rug pulls or liquidity drains. Fund manager wallets are voted in by a
                governance process to prevent external manipulation of funds.
                {PARAGRAPH_BREAK}
                The smart contract is openly auditable&nbsp;
                <a href="www.google.com" className="text-blue-600 underline cursor-pointer">
                    here
                </a>
                . Please note that the &quot;token value&quot; does not represent the AUM within
                Transparent, as it does not include non BEP-20 tokens, such as Pancake Swap LP
                tokens.
            </>
        )
    },
    {
        title: 'Risks involved',
        text: (
            <>
                Due to the complexity of the strategies employed by Transparent (arbitrage,
                statistical arbitrage, events-based trading, DAO ventures), we highly recommended
                against retail investors from buying and holding Transparent without a thorough
                understanding of the kind of risks that might arise from holding Transparent. A
                breakdown of the risks and mitigations measures can be found within the Transparent
                Whitepaper.
                {PARAGRAPH_BREAK}
                Even the most ardent holders should only seek to diversify their total portfolio
                with a controlled and informed allocation of Transparent. There is a possibility to
                incur losses, perhaps even a complete and total loss.
                {PARAGRAPH_BREAK}
                Transparent does not take responsibility for any losses that might potentially arise
                from holding the token. While the team will perform responsible and principled
                risk-taking, it cannot guarantee the absence of catastrophic and complete losses
            </>
        )
    },
    {
        title: 'Liquidity',
        text: (
            <>
                Actual amount for liquidity available for monthly withdrawal is up to the
                protocol&apos;s discretion. More generally, up to 5% of Transparent AUM will be
                converted to BUSD for withdrawals up till the 5% has been exhausted, then the
                withdrawals will be gated until the following month. However, no liquidity is
                guaranteed by Transparent.
                {PARAGRAPH_BREAK}
                Liquidity can still be achieved by selling Transparent on DEXes, or with other
                wallets.
            </>
        )
    },
    {
        title: 'Indemnification by Holders',
        text: (
            <>
                Holders of Transparent Token agrees to indemnify and hold harmless the project team,
                and each person, but only insofar as such loss, liability, claim, damage or expense
                arises out of or is based upon usage of Transparent, a decrease in token value,
                withdrawal gates or any untrue statement or omission, or alleged untrue statement or
                omission, made in the Disclaimer, Whitepaper or the Website.
            </>
        )
    }
];

type DisclaimerProps = {
    callback: () => Promise<void>;
};

/**
 * The disclaimer modal component.
 *
 * @param {DisclaimerProps} props - The callback after acknowledging.
 * @returns {ReactElement} - The disclaimer component.
 */
const Disclaimer: FC<DisclaimerProps> = ({ callback }: DisclaimerProps): ReactElement => {
    const { isDisclaiming, setDisclaimed } = useWeb3Context();
    const [isScrolledToBottom, setIsScrolledToBottom] = useState<boolean>(false);
    const [isAcknowledged, setIsAcknowledged] = useState<boolean>(false);

    /** Render callback to bind the onScroll callback to the terms box div */
    const termsScrollableBoxRef = useCallback((divElement: HTMLDivElement) => {
        const onScroll = () => {
            setIsScrolledToBottom(
                divElement.scrollHeight - divElement.scrollTop === divElement.clientHeight
            );
        };

        if (divElement) {
            console.log('scrollto');
            divElement.scrollTo(0, 0);
            divElement.addEventListener('scroll', onScroll);
        }
    }, []);

    return (
        <Modal
            isOpen={isDisclaiming}
            contentStyle={{
                width: '70%',
                maxWidth: '920px',
                height: 'auto'
            }}
            closeOnDocumentClick={false}>
            <div className="h-full w-full text-base lg:text-lg">
                <p className="w-full text-center font-bold underline">
                    Transparent Protocol Disclaimer
                </p>
                <div className="h-2"></div>
                <p className="w-full px-10 text-center leading-6">
                    All investing comes with risk. It&apos;s important to do your own research.
                </p>
                <div className="h-6"></div>
                <div
                    ref={termsScrollableBoxRef}
                    className="h-60% max-h-[360px] md:max-h-[460px] p-5 bg-gray-300 overflow-y-auto">
                    {/* Force initial focus at top */}
                    <a href="" className="hidden">
                        top
                    </a>
                    <ol className="list-decimal list-outside ml-5 space-y-8">
                        {PARAGRAPHS.map((paragraph) => (
                            <li key={paragraph.title} className="leading-6">
                                <span className="underline">{paragraph.title}</span>.&nbsp;
                                <span className="disclaimer-text">{paragraph.text}</span>
                            </li>
                        ))}
                    </ol>
                </div>
                <div className="h-6"></div>
                <div className="w-11/12 lg:w-5/6 mx-auto">
                    <p className="font-semibold text-center leading-6">
                        Never invest more than you can lose - you alone are responsible for your
                        investment. Transparent is NOT responsible for any losses or changes in
                        token value, and NOT responsible for any lost funds due to smart contract
                        error or exploits.
                    </p>
                </div>
                <div className="h-6"></div>
                <div>
                    <label htmlFor="isAcknowledged" className="flex items-center justify-center">
                        <input
                            id="isAcknowledged"
                            className="h-5 w-5"
                            type="checkbox"
                            checked={isAcknowledged}
                            disabled={!isScrolledToBottom}
                            onChange={() => setIsAcknowledged(!isAcknowledged)}
                        />
                        <span className="text-sm lg:text-base">
                            &nbsp;&nbsp;I hereby acknowledge and agree to the terms described above.
                        </span>
                    </label>
                    <p className="text-center text-sm lg:text-base text-red-600 italic">
                        Please finish reading before acknowledging.
                    </p>
                </div>
                <div className="h-6"></div>
                <div className="w-full flex justify-end">
                    <button
                        className="px-3 py-2 bg-blue-700 text-white rounded-md shadow-md
                        disabled:opacity-50 disabled:cursor-not-allowed"
                        disabled={!isAcknowledged}
                        onClick={async () => {
                            setDisclaimed();
                            await callback();
                        }}>
                        Proceed
                    </button>
                </div>
            </div>
        </Modal>
    );
};

export default Disclaimer;
